/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'cms',
    path: '/cms',
    component: 'layout.base',
    meta: {
      title: '内容管理',
      icon: 'mdi:file-document-edit-outline',
      order: 2,
      i18nKey: 'route.cms'
    },
    children: [
      {
        name: 'cms_nav',
        path: '/cms/nav',
        component: 'view.cms_nav',
        meta: {
          title: '导航菜单',
          icon: 'mdi:menu',
          order: 1,
          i18nKey: 'route.cms_nav',
          roles: ['R_SUPER', 'R_ADMIN']
        }
      },
      {
        name: 'cms_content',
        path: '/cms/content',
        component: 'view.cms_content',
        meta: {
          title: '页面内容',
          icon: 'mdi:file-document-outline',
          order: 2,
          i18nKey: 'route.cms_content'
        }
      },
      {
        name: 'cms_news',
        path: '/cms/news',
        component: 'view.cms_news',
        meta: {
          title: '新闻动态',
          icon: 'mdi:newspaper-variant-outline',
          order: 3,
          i18nKey: 'route.cms_news'
        }
      }
    ]
  },
  {
    name: 'config',
    path: '/config',
    component: 'layout.base',
    meta: {
      title: '系统管理',
      icon: 'mdi:shield-account-outline',
      order: 3,
      i18nKey: 'route.config',
      roles: ['R_SUPER', 'R_ADMIN']
    },
    children: [
      {
        name: 'config_home',
        path: '/config/home',
        component: 'view.config_home',
        meta: {
          title: '首页配置',
          icon: 'mdi:home-edit-outline',
          order: 1,
          i18nKey: 'route.config_home',
          roles: ['R_SUPER', 'R_ADMIN']
        }
      },
      {
        name: 'config_files',
        path: '/config/files',
        component: 'view.config_files',
        meta: {
          title: '文件管理',
          icon: 'mdi:folder-multiple-outline',
          order: 2,
          i18nKey: 'route.config_files',
          roles: ['R_SUPER', 'R_ADMIN']
        }
      },
      {
        name: 'manage_users',
        path: '/manage/users',
        component: 'view.manage_users',
        meta: {
          title: '用户管理',
          icon: 'mdi:account-group-outline',
          order: 3,
          i18nKey: 'route.manage_users',
          roles: ['R_SUPER', 'R_ADMIN']
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  }
];
